name: Server CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Package
        run: |
          cd client
          npm install
      - name: Test client
        run: |
          cd client
          npm run build --if-present
      - name: Lint with eslint (typesciprt)
        run: |
          cd client
          npm run lint
      # - name: Test react
      #   run: |
      #     make test-server